#!/bin/bash
# Description:
#  Build a Lightweight Alpine-Based Docker Image for Hugo
# Requires:
# - 'docker'    : https://www.docker.com
# - 'git'       : https://git-scm.com
# Environments:
# - $IMAGE_NAME : The name of the Docker Image
# - $VERSION    : The version of the Docker Image

echo "Building Docker Image: ${IMAGE_NAME}"

BUILD_HUGO_VERSION=""

if [ "${VERSION}" == "" ]
then
  echo "Building Version: latest"
  HUGO_VERSION=`cat README.md | sed -n "s/Latest build contains the Hugo v\([0-9.]\+\)/\1/p"`
  echo "Hugo Version: ${HUGO_VERSION}"
  BUILD_HUGO_VERSION="--build-arg HUGO_VERSION=${HUGO_VERSION}"
else
  echo "Building Version: ${VERSION}"
fi

docker build \
--build-arg VCS_REF=`git rev-parse --short HEAD` \
--build-arg VCS_URL=`git config --get remote.origin.url` \
--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
$BUILD_HUGO_VERSION \
-t $IMAGE_NAME .